### ISSUE TITLE
Working with single files

### ISSUE THREAD

**Issue by naveedhd** [joelabair/multer-autoreap#10]
When using `multer.single`, the resulting request is `file` and not `files` which seems to be not handled currently in the package. 

For now I have done it manually for my purpose from the source of the package.

**Comment by joelabair** [comment]
Are you using the upload.single handler in multer?

**Comment by joelabair** [comment]
@naveedhd does multer-autoreap@0.1.0 fix the issue for you?

**Comment by naveedhd** [comment]
@joelabair yes I am using upload.single handler.

**Comment by naveedhd** [comment]
Let me test with @0.1.0.

**Comment by naveedhd** [comment]
@joelabair I tested with @0.1.0. It works fine!

**Comment by naveedhd** [comment]
solved by [PR](https://github.com/joelabair/multer-autoreap/commit/cb953f6cb289a58bb9f7a09c94257e7f6b25e0e6)

**Comment by joelabair** [comment]
Awesome! Thanks for raising this issue, and providing me the opportunity to resolve it.
