### ISSUE TITLE
Option to prevent reaping

### ISSUE THREAD

**Issue by TomMettam** [joelabair/multer-autoreap#12]
I want to use this to clean up any files after a failed upload or timeout.

However, upon a successful upload, I need to use the uploaded file for async operations. It would be nice to be able to set something like..

res.dontReap = true;

once I've confirmed the upload is successful and the file is valid, to prevent the file from getting cleaned. I've worked around it by copying the file to another location, but i'd prefer to avoid this copy operation.

**Comment by joelabair** [comment]
This was the initial intention of the tool.  You either process files and they get cleaned up automagically, or move them to a location for asynchronous processing and clean them up yourself.  I can see how this option could be useful, however.  If nothing else, for debugging some failure in processing.

**Comment by thegauravtiwari** [comment]
Can files be removed using multer-autoreap when user sends a request to do so? @joelabair
