### ISSUE TITLE
Deletes files too soon

### ISSUE THREAD

**Issue by nighk** [joelabair/multer-autoreap#13]
Autoreap was deleting files before my app had finished processing them. I added a 10 second delay into the reapFiles method in index.js which solved the issue. It would be good if something like this could be included into the package to prevent others having this issue.

**Comment by joelabair** [comment]
autoreap uses the request close or error events to trigger deleting files.  See https://www.npmjs.com/package/finished

You are likely processing your files outside of the request event loop via an asycn callback, I.e. in a nextTick or post DB query promise.  And this isn't really a best use case for "AutoReap", in its current design. 
 
A better solution may be to support triggering auto-reap on a custom event name.  via the options config.

**Comment by nighk** [comment]
Yes I am using async method calls. I will look into using a custom event name. Thanks.

**Comment by joelabair** [comment]
well - I would need to add custom event name support to the api.  that's not an existing feature.

the simple solution is to move the files you want to process to a processing dir, and then reap them on you own.  autoreap only deletes tmp files.  just another suggestion.

**Comment by nighk** [comment]
Yes I did think of that, but it is difficult when using Async methods as I can't be certain which one will finish first :-D Perhaps the time delay is the easiest solution, even though it's a bit of a hack.

Although I have found an Asyc module for NodeJS which looks like it might solve the issue: http://www.sebastianseilund.com/nodejs-async-in-practice. Then I'll just reap the files after myself, or use your custom event name if you have time to do it ;-)
