### ISSUE TITLE
Deprecation warning with node v7.0.0

### ISSUE THREAD

**Issue by tadessetdk** [joelabair/multer-autoreap#16]
DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:103:12)
    at Object.fs.unlink (fs.js:979:14)
    multer-autoreap\index.js:26:8

**Comment by joelabair** [comment]
Please provide information about your environment.  
OS
node version
express version
multer version

**Comment by joelabair** [comment]
Never mind.  I got it. Fixed in 1.3 release. Thanks for pointing this out

**Comment by tadessetdk** [comment]
Great. I will use the latest version.

--Thanks
