### ISSUE TITLE
Order of deletion

### ISSUE THREAD

**Issue by eugenekgn** [joelabair/multer-autoreap#17]
What if I have something like this 

```router.post('/upload-file/', multer.single('file'), autoReap, uploadMedia(req)));```

Will this work?

I need to process file before I can delete it, what's the best way to go about this?

Eugene

**Comment by joelabair** [comment]
auto-reap removes uploaded files when the request ends (on finished).  

AutoReap is basically just attaching a listener for the end/finished events on the req object. So, it wouldn't really matter which order in the chain you add autoReap, as long as its not the last middleware.
