### ISSUE TITLE
TypeError: Cannot read property 'socket' of undefined at isFinished

### ISSUE THREAD

**Issue by wahyubucil** [joelabair/multer-autoreap#18]
<img width="960" alt="screen shot 2018-07-18 at 8 51 13 pm" src="https://user-images.githubusercontent.com/30768993/42882878-89a931b4-8acc-11e8-9c0d-acea3509fce8.png">

I get that error while use this middleware

Node: v8.11.3

Thanks in advance :)

**Comment by wahyubucil** [comment]
Sorry. It was my fault
I used it on the routes. So i think it need to use like this: `autoReap()`

But actually. I just need to use it like this: `autoReap`

Thanks for this awesome library :)

**Comment by joelabair** [comment]
Interesting.  I had not though of the use case of attaching the middleware to a route.  I'll have to build a test case and some example code for attaching to a route.  Thanks for raising this issue.
