### ISSUE TITLE
The elements in req.files may be arrays

### ISSUE THREAD

**Issue by JcBernack** [joelabair/multer-autoreap#7]
The elements in req.files may already be arrays which will cause an exception in autoreap. Soon the current behavior will be deprecated and the elements will always be arrays.

See https://www.npmjs.com/package/multer#putsinglefilesinarray

**Comment by JcBernack** [comment]
Just notices that there is already a pull-request #6 pending.

**Comment by joelabair** [comment]
@JcBernack I just merged PR #6.  closing...

**Comment by lucastan** [comment]
can you create a new NPM version for fixes so far?

**Comment by joelabair** [comment]
@lucastan 0.0.9 published on 6/15/15  includes the latest fixes.
