### ISSUE TITLE
NPM/GitHub out of Sync

### ISSUE THREAD

**Issue by Bipsy** [joelabair/multer-autoreap#8]
I noticed that the version available on npm does not include the fix patched in about a month ago. This is a breaking point for an application that I work on.

**Comment by joelabair** [comment]
Oops - hang on.  Which patch?

**Comment by joelabair** [comment]
So sorry about that. Thought I pushed this a month ago.

Released 0.0.9
Published NPM multer-autoreap-0.0.9

**Comment by joelabair** [comment]
Thanks for the heads-up @Bipsy
