### ISSUE TITLE
Files not removed on crash

### ISSUE THREAD

**Issue by rrNuvoPoint** [joelabair/multer-autoreap#9]
I work on a cluster setup. Sometimes an err occur and the worker will crash.
Then the files are not deleted. Any ideas to implement that improvement?

**Comment by joelabair** [comment]
I hadn't considered that feature as the point of this is to manage operational baggage, and not intended as a stopgap for error conditions. 

Implementing with this module, would depend on the point of crash.  We have no guarantee that the files info persists at the point when process.exit happens.  

Probably better to implement this on your cluster initialization, adding a listener to each worker.  You'll need to label/flag the files in use by a particular worker (adding the worker id to the upload path may work) and remove the upload dir on worker.exit().
